server:
  port: 8084
spring:
  datasource:
    url: jdbc:h2:mem:restdb
  data:
    rest:
      base-path: /rest/api
  jpa:
    show-sql: true
logging:
  level:
    org.springframework.data.rest: DEBUG
#    org.hibernate: DEBUG

---

spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_ON_EXIT=FALSE
